apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-server-app-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preview-server-app
      environment: testing
  template:
    metadata:
      labels:
        app: preview-server-app
        environment: testing
    spec:
      containers:
        - name: preview-server
          image: 684910554524.dkr.ecr.us-west-2.amazonaws.com/preview-server:latest
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 70
            timeoutSeconds: 10
            failureThreshold: 10
